# -*- coding: utf-8 -*-
"""analysis_feature_with_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c53MqJU9tspYaefFtQKiKYl48p1mVOAy
"""

"""
analysis_feature_agreement.py

Two separate analyses:

A) Human × Model agreement
   For each morphological feature and each context: build two probability
   distributions over feature values (one from human predictions, one from
   model predictions) and compare them.
   Metrics:
     A1 — per-value Pearson/Spearman correlation across 144 contexts
          (analogous to POS Algorithm 2)
     A2 — mean absolute delta per context
          (analogous to POS Algorithm 3)

B) × Target accuracy
   For each feature: what fraction of predictions (human / model separately)
   match the target word's value of that feature.
   Uses the already-computed feature_accuracy / feature_intersection columns
   directly — no re-parsing needed.

Outputs → output/feature_agreement/
"""

import ast
import pathlib

import numpy as np
import pandas as pd
from scipy import stats

from filter_data_llama_6 import load_gpt, load_human

OUT = pathlib.Path("output/feature_agreement")
OUT.mkdir(parents=True, exist_ok=True)

FEATURES = ["Case", "Number", "Gender", "Tense", "Aspect", "Animacy", "VerbForm"]

human_raw = load_human()
model_raw = load_gpt()

context_lookup = (
    human_raw.drop_duplicates("word.id")[["word.id", "Left context"]]
    .rename(columns={"word.id": "target_word", "Left context": "left_context"})
)

# format: "Case=Nom|Number=Sing|Gender=Masc|..."  or NaN
def parse_feats(val) -> dict:
    if not isinstance(val, str) or not val.strip():
        return {}
    out = {}
    for item in val.split("|"):
        if "=" in item:
            k, v = item.split("=", 1)
            out[k.strip()] = v.strip()
    return out

human_raw = human_raw.copy()
model_raw = model_raw.copy()

human_raw["feats_dict"] = human_raw["feats_answer"].apply(parse_feats)
model_raw["feats_dict"] = model_raw["feats"].apply(parse_feats)


# B) × TARGET ACCURACY
# Already computed in feature_accuracy (human) / feature_intersection (model)
# Format: list of strings like ['Case=Nom', 'Number=Sing']

def parse_accuracy_list(val) -> list:
    if isinstance(val, list):
        return val
    if isinstance(val, str):
        val = val.strip()
        if val.startswith("["):
            return ast.literal_eval(val)
        return []
    return []

human_raw["acc_list"] = human_raw["features_accuracy"].apply(parse_accuracy_list)
model_raw["acc_list"] = model_raw["feature_accuracy"].apply(parse_accuracy_list)

# parse target feats  (same format as feats, stored in mapped_feats_ud / target_mapped_feats_ud)
# format: "{'NOUN', 'Case=Nom', 'Gender=Fem', ...}"  — set repr as string
def parse_target_feats(val) -> dict:
    if isinstance(val, dict):
        return val
    if not isinstance(val, str):
        return {}
    out = {}
    # strip outer braces, split by comma, keep only Key=Value items
    for item in val.strip("{}").split(","):
        item = item.strip().strip("'\"")
        if "=" in item:
            k, v = item.split("=", 1)
            out[k.strip()] = v.strip()
    return out

human_raw["target_feats"] = human_raw["mapped_feats_ud"].apply(parse_target_feats)
model_raw["target_feats"] = model_raw["target_mapped_feats_ud"].apply(parse_target_feats)

def target_accuracy_per_feature(df, acc_col, prob_col, group_col, label):
    """
    For each feature: fraction of predictions where that feature matched target.
    Two sub-metrics:
      - unweighted: each prediction counts equally (raw match rate)
      - weighted:   weighted by prediction probability (prob_col)
    Also broken down per context → mean across contexts.
    """
    records = []
    for feat in FEATURES:
        # rows where target has this feature
        has_feat = df["target_feats"].apply(lambda d: feat in d)
        sub = df[has_feat].copy()
        if len(sub) == 0:
            continue

        # did this prediction match on this feature?
        sub["matched"] = sub[acc_col].apply(
            lambda lst: any(item.startswith(feat + "=") for item in lst)
        )

        # unweighted
        unweighted = sub["matched"].mean()

        # weighted by probability
        total_prob = sub[prob_col].sum()
        weighted = (sub["matched"] * sub[prob_col]).sum() / total_prob if total_prob > 0 else np.nan

        # per-context mean (unweighted within context, then mean across contexts)
        per_ctx = sub.groupby(group_col)["matched"].mean()
        per_ctx_mean = per_ctx.mean()

        records.append({
            "feature": feat,
            "n_predictions": len(sub),
            "n_contexts": sub[group_col].nunique(),
            "match_rate_unweighted": round(unweighted, 4),
            "match_rate_weighted": round(weighted, 4),
            "match_rate_per_ctx_mean": round(per_ctx_mean, 4),
        })

    out = pd.DataFrame(records)
    out.to_csv(OUT / f"target_accuracy_{label}.csv", index=False)
    print(f"\n=== B) ×Target accuracy ({label}) ===")
    print(out.to_string(index=False))
    return out


acc_human = target_accuracy_per_feature(
    human_raw, "acc_list", "probability_y", "word.id", "human"
)
acc_model = target_accuracy_per_feature(
    model_raw, "acc_list", "probability_converted", "target_word_id", "model"
)

# combined comparison table
acc_compare = acc_human[["feature", "match_rate_per_ctx_mean"]].merge(
    acc_model[["feature", "match_rate_per_ctx_mean"]],
    on="feature", suffixes=("_human", "_model")
)
acc_compare["delta_human_minus_model"] = (
    acc_compare["match_rate_per_ctx_mean_human"]
    - acc_compare["match_rate_per_ctx_mean_model"]
).round(4)
acc_compare.to_csv(OUT / "target_accuracy_comparison.csv", index=False)
print("\n=== B) ×Target accuracy: human vs model ===")
print(acc_compare.to_string(index=False))


# A) HUMAN × MODEL AGREEMENT
# For each feature and context: build prob distributions over feature values,
# compare human vs model.

# deduplicate: one row per (context, prediction)
human_dedup = (
    human_raw.groupby(["word.id", "answer"], as_index=False)
    .first()[["word.id", "answer", "feats_dict", "probability_y"]]
)
model_dedup = (
    model_raw.sort_values("probability_converted", ascending=False)
    .drop_duplicates(subset=["target_word_id", "prediction_cleaned"], keep="first")[
        ["target_word_id", "prediction_cleaned", "feats_dict", "probability_converted"]
    ]
)

def build_feature_value_matrix(df, group_col, prob_col, feat):
    """
    Returns DataFrame: index=context, columns=feature values,
    values=sum of probability for that feature value in that context.
    Only keeps rows where the prediction has this feature.
    """
    # extract value of this feature for each prediction
    df = df.copy()
    df["feat_val"] = df["feats_dict"].apply(lambda d: d.get(feat, None))
    df_has = df[df["feat_val"].notna()]
    if len(df_has) == 0:
        return pd.DataFrame()
    mat = (
        df_has.groupby([group_col, "feat_val"])[prob_col]
        .sum()
        .unstack(fill_value=0)
    )
    mat.index.name = "context"
    return mat


all_results_corr  = []
all_results_delta = []

for feat in FEATURES:
    h_mat = build_feature_value_matrix(human_dedup, "word.id", "probability_y", feat)
    m_mat = build_feature_value_matrix(model_dedup, "target_word_id", "probability_converted", feat)

    if h_mat.empty or m_mat.empty:
        continue

    # align: same contexts and same feature values
    all_vals = sorted(set(h_mat.columns) | set(m_mat.columns))
    all_ctx  = sorted(set(h_mat.index)   & set(m_mat.index))   # intersection of contexts

    if len(all_ctx) < 10:
        continue

    h_mat = h_mat.reindex(index=all_ctx, columns=all_vals, fill_value=0)
    m_mat = m_mat.reindex(index=all_ctx, columns=all_vals, fill_value=0)

    # ── A1: per-value correlation across contexts 
    for val in all_vals:
        h_vec = h_mat[val].values
        m_vec = m_mat[val].values
        n_ctx = int(np.sum((h_vec > 0) | (m_vec > 0)))
        if n_ctx < 10:
            continue
        if np.std(h_vec) == 0 or np.std(m_vec) == 0:
            continue
        pr, pp = stats.pearsonr(h_vec, m_vec)
        sr, sp = stats.spearmanr(h_vec, m_vec)
        all_results_corr.append({
            "feature": feat,
            "value": val,
            "n_contexts": n_ctx,
            "pearson_r": round(pr, 4),
            "pearson_p": round(pp, 6),
            "spearman_r": round(sr, 4),
            "spearman_p": round(sp, 6),
        })

    # ── A2: delta per context
    delta_mat = (h_mat - m_mat).abs()
    mean_delta_per_ctx = delta_mat.mean(axis=1)       # mean over values, per context
    mean_delta_per_val = delta_mat.mean(axis=0)       # mean over contexts, per value
    overall_delta = mean_delta_per_ctx.mean()

    for val in all_vals:
        all_results_delta.append({
            "feature": feat,
            "value": val,
            "mean_delta": round(float(mean_delta_per_val[val]), 4),
            "n_contexts": len(all_ctx),
        })

    # save per-feature delta detail
    delta_out = pd.DataFrame({
        "context": all_ctx,
        "mean_delta_across_values": mean_delta_per_ctx.values,
    })
    delta_out = delta_out.merge(
        context_lookup.rename(columns={"target_word": "context"}),
        on="context", how="left"
    )
    delta_out.to_csv(OUT / f"human_model_delta_{feat}.csv", index=False)


corr_df = pd.DataFrame(all_results_corr).sort_values(
    ["feature", "pearson_r"], ascending=[True, False]
)
corr_df.to_csv(OUT / "human_model_feature_correlation.csv", index=False)

print("\n A1) Human × Model feature-value correlation ")
print(corr_df.to_string(index=False))

delta_df = pd.DataFrame(all_results_delta).sort_values(
    ["feature", "mean_delta"], ascending=[True, False]
)
delta_df.to_csv(OUT / "human_model_feature_delta.csv", index=False)

print("\n=== A2) Human × Model feature-value delta ===")
print(delta_df.to_string(index=False))

# ── summary: one row per feature 
summary_rows = []
for feat in FEATURES:
    sub_corr  = corr_df[corr_df["feature"] == feat]
    sub_delta = delta_df[delta_df["feature"] == feat]
    if sub_corr.empty:
        continue
    summary_rows.append({
        "feature": feat,
        "mean_pearson_r":    round(sub_corr["pearson_r"].mean(), 4),
        "max_pearson_r":     round(sub_corr["pearson_r"].max(), 4),
        "mean_delta":        round(sub_delta["mean_delta"].mean(), 4),
        "n_values":          len(sub_corr),
    })

summary = pd.DataFrame(summary_rows)
summary.to_csv(OUT / "human_model_feature_summary.csv", index=False)

print("\n=== Summary: Human × Model agreement per feature ===")
print(summary.to_string(index=False))
print(f"\nOutputs saved to {OUT}/")
