# -*- coding: utf-8 -*-
"""analysis_pos_corr_with_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c53MqJU9tspYaefFtQKiKYl48p1mVOAy
"""

import pathlib
import warnings
!pip install pymorphy3
# Попытка установить pymorphy3 (для сред, где pip доступен)

import pymorphy3
MORPH = pymorphy3.MorphAnalyzer()
PYMO_AVAILABLE = True


import matplotlib
matplotlib.use("Agg")
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

from filter_data_llama_6 import get_all_models, load_human

# ─
# Функция для получения оригинального тега pymorphy (например, 'NOUN', 'ADJF', ...)
def get_pymorphy_tag(word: str) -> str:
    if not PYMO_AVAILABLE or not isinstance(word, str) or not word.strip():
        return None
    parsed = MORPH.parse(word)[0]
    pos = parsed.tag.POS
    return str(pos) if pos is not None else None   # исходный тег

# ─
MIN_CONTEXTS = 10
ROOT = pathlib.Path("output/pos_corr")

TAGGERS = [
    ("stanza",   "upos_answer", "upos_word"),
    ("pymorphy", "pymorphy_pos", "pymorphy_pos"),
]

COMBO_COLORS = {
    ("stanza",   "GPT-4o-mini"): "#2166ac",
    ("stanza",   "Llama"):       "#4393c3",
    ("pymorphy", "GPT-4o-mini"): "#d6604d",
    ("pymorphy", "Llama"):       "#f4a582",
}

human_raw = load_human()

context_lookup = (
    human_raw.drop_duplicates("word.id")[["word.id", "Left context"]]
    .rename(columns={"word.id": "target_word", "Left context": "left_context"})
)


def build_pos_matrix(df, group_col, pos_col, prob_col, all_contexts, all_pos):
    mat = (
        df.groupby([group_col, pos_col])[prob_col]
        .sum()
        .unstack(fill_value=0)
    )
    mat.index.name = "word_id"
    return mat.reindex(index=all_contexts, columns=all_pos, fill_value=0)


def add_context_cols(pos_df, context_lookup):
    df = pos_df.reset_index().rename(columns={"word_id": "target_word"})
    df = df.merge(context_lookup, on="target_word", how="left")
    cols = ["left_context", "target_word"] + [
        c for c in df.columns if c not in ("left_context", "target_word")
    ]
    return df[cols]


def run_corr(human_df, model_df, human_col, model_col, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)

    human = (
        human_df.groupby(["word.id", "answer"])
        .first()
        .reset_index()[["word.id", "answer", human_col, "probability_y"]]
    )

    model = (
        model_df.dropna(subset=[model_col])
        .sort_values("probability_converted", ascending=False)
        .drop_duplicates(subset=["target_word_id", "prediction_cleaned"], keep="first")[
            ["target_word_id", "prediction_cleaned", model_col, "probability_converted"]
        ]
    )

    all_pos = sorted(
        set(human[human_col].dropna()) | set(model[model_col].dropna())
    )
    all_contexts = sorted(
        set(human["word.id"]) | set(model["target_word_id"])
    )

    human_pos = build_pos_matrix(
        human, "word.id", human_col, "probability_y", all_contexts, all_pos
    )
    model_pos = build_pos_matrix(
        model, "target_word_id", model_col, "probability_converted", all_contexts, all_pos
    )

    print(f"  POS tags ({len(all_pos)}): {all_pos}")

    rows = []
    for pos in all_pos:
        h_vec = human_pos[pos].values
        m_vec = model_pos[pos].values
        n_ctx = int(np.sum((h_vec > 0) | (m_vec > 0)))
        if n_ctx < MIN_CONTEXTS:
            continue
        if np.std(h_vec) == 0 or np.std(m_vec) == 0:
            continue
        pr, pp = stats.pearsonr(h_vec, m_vec)
        sr, sp = stats.spearmanr(h_vec, m_vec)
        rows.append({
            "pos_tag":    pos,
            "n_contexts": n_ctx,
            "pearson_r":  round(pr, 4),
            "pearson_p":  round(pp, 6),
            "spearman_r": round(sr, 4),
            "spearman_p": round(sp, 6),
        })

    corr_df = pd.DataFrame(rows).sort_values("pearson_r", ascending=False)
    corr_df.to_csv(out_dir / "per_pos_correlation.csv", index=False)
    print("\n=== Algorithm 2: per-POS correlation ===")
    print(corr_df.to_string(index=False))
    # also delta table but it doesnt used in the analysis
    delta = (human_pos - model_pos).abs()
    mean_delta_per_context = delta.mean(axis=1)
    overall_mean_delta = mean_delta_per_context.mean()

    delta_out = pd.DataFrame({
        "target_word": all_contexts,
        "mean_delta": mean_delta_per_context.values,
    })
    for pos in all_pos:
        delta_out[pos] = delta[pos].values
    delta_out = delta_out.merge(context_lookup, on="target_word", how="left")
    cols = ["left_context", "target_word"] + [
        c for c in delta_out.columns if c not in ("left_context", "target_word")
    ]
    delta_out[cols].to_csv(out_dir / "per_context_delta.csv", index=False)

    print(f"\n=== Algorithm 3: delta-table ===")
    print(f"  Overall mean delta: {overall_mean_delta:.4f}")
    print(f"  Per-context: min={mean_delta_per_context.min():.4f}, "
          f"max={mean_delta_per_context.max():.4f}")


    add_context_cols(human_pos, context_lookup).to_csv(
        out_dir / "human_pos_matrix.csv", index=False
    )
    add_context_cols(model_pos, context_lookup).to_csv(
        out_dir / "model_pos_matrix.csv", index=False
    )

    pd.DataFrame({"overall_mean_delta": [round(overall_mean_delta, 4)]}).to_csv(
        out_dir / "summary.csv", index=False
    )

    _plot_correlation(corr_df, out_dir / "fig_correlation.png")
    _plot_delta(delta, mean_delta_per_context, overall_mean_delta,
                out_dir / "fig_delta.png")

    return corr_df, delta, mean_delta_per_context, overall_mean_delta



def _plot_correlation(corr_df, out_path):
    corr_plot = corr_df.sort_values("pearson_r", ascending=True)
    tags  = corr_plot["pos_tag"].tolist()
    r_val = corr_plot["pearson_r"].tolist()

    fig, ax = plt.subplots(figsize=(8, max(4, len(tags) * 0.45)))
    bars = ax.barh(tags, r_val, color="#2166ac", edgecolor="white", height=0.65)
    for bar, val in zip(bars, r_val):
        sign = "+" if val >= 0 else ""
        ax.text(
            val + (0.015 if val >= 0 else -0.015),
            bar.get_y() + bar.get_height() / 2,
            f"{sign}{val:.2f}", va="center",
            ha="left" if val >= 0 else "right", fontsize=8.5,
        )
    ax.axvline(0, color="black", linewidth=0.8)
    ax.set_xlabel("Pearson r", fontsize=10)
    ax.set_title("Алгоритм 2: корреляция POS-распределений\n(Human × Model)", fontsize=10)
    ax.grid(axis="x", alpha=0.3)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close()


def _plot_delta(delta, mean_delta_per_context, overall_mean_delta, out_path):
    pos_cols = list(delta.columns)
    delta_per_pos = delta[pos_cols].mean().sort_values(ascending=False)
    delta_per_pos = delta_per_pos[delta_per_pos > 0.001]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # left: delta per POS tag
    ax = axes[0]
    ax.bar(range(len(delta_per_pos)), delta_per_pos.values,
           color="#2166ac", alpha=0.8, edgecolor="white")
    ax.axhline(overall_mean_delta, color="#b2182b", lw=1.8, linestyle="--",
               label=f"overall Δ = {overall_mean_delta:.4f}")
    ax.set_xticks(range(len(delta_per_pos)))
    ax.set_xticklabels(delta_per_pos.index.tolist(), rotation=35, ha="right", fontsize=8.5)
    ax.set_ylabel("Mean |Δ|", fontsize=10)
    ax.set_title("Среднее |Δ| по тегам", fontsize=10)
    ax.legend(fontsize=8.5)
    ax.grid(axis="y", alpha=0.3)
    for i, v in enumerate(delta_per_pos.values):
        ax.text(i, v + 0.003, f"{v:.3f}", ha="center", fontsize=7.5)

    # right: histogram of per-context mean delta
    ax = axes[1]
    ax.hist(mean_delta_per_context.values, bins=20, color="#4393c3",
            edgecolor="white", alpha=0.85)
    ax.axvline(overall_mean_delta, color="#b2182b", lw=2, linestyle="--",
               label=f"mean = {overall_mean_delta:.4f}")
    ax.set_xlabel("Mean |Δ| per context", fontsize=10)
    ax.set_ylabel("Число контекстов", fontsize=10)
    ax.set_title("Распределение Δ по контекстам", fontsize=10)
    ax.legend(fontsize=8.5)
    ax.grid(alpha=0.3)

    plt.suptitle("Алгоритм 3: delta-таблица", fontsize=11, y=1.01)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close()


def plot_correlation_all(all_corr: dict, out_path: pathlib.Path):
    all_tags = sorted(set(tag for df in all_corr.values() for tag in df["pos_tag"]))
    fig, ax = plt.subplots(figsize=(10, max(5, len(all_tags) * 0.55)))
    markers = ["o", "s", "^", "D"]
    for (label, corr_df), marker in zip(all_corr.items(), markers):
        tagger, model = label.split(" — ")
        color = COMBO_COLORS.get((tagger, model), "#888888")
        tag_to_r = dict(zip(corr_df["pos_tag"], corr_df["pearson_r"]))
        xs = [tag_to_r.get(t, np.nan) for t in all_tags]
        ys = list(range(len(all_tags)))
        ax.scatter(xs, ys, color=color, s=70, marker=marker,
                   label=label, zorder=3, alpha=0.9)
    ax.set_yticks(range(len(all_tags)))
    ax.set_yticklabels(all_tags, fontsize=8.5)
    ax.axvline(0, color="black", lw=0.8)
    ax.axvline(0.5, color="gray", lw=0.7, linestyle=":", alpha=0.6)
    ax.set_xlabel("Pearson r (Human × Model)", fontsize=10)
    ax.set_title("Алгоритм 2: корреляция POS-распределений\n"
                 "stanza vs pymorphy3, GPT-4o-mini vs Llama", fontsize=11)
    ax.legend(fontsize=8.5, framealpha=0.9)
    ax.grid(axis="x", alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_path, dpi=160, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {out_path}")


def plot_delta_all(all_delta_summary: dict, out_path: pathlib.Path):
    labels = list(all_delta_summary.keys())
    values = [all_delta_summary[l] for l in labels]
    colors = [COMBO_COLORS.get(tuple(l.split(" — ")), "#888888") for l in labels]
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.bar(range(len(labels)), values, color=colors, edgecolor="white", width=0.6)
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=15, ha="right", fontsize=9)
    ax.set_ylabel("Overall mean |Δ|", fontsize=10)
    ax.set_title("Алгоритм 3: общее среднее расхождение\n"
                 "stanza vs pymorphy3, GPT-4o-mini vs Llama", fontsize=11)
    ax.grid(axis="y", alpha=0.3)
    for i, v in enumerate(values):
        ax.text(i, v + 0.001, f"{v:.4f}", ha="center", fontsize=9)
    plt.tight_layout()
    plt.savefig(out_path, dpi=160, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {out_path}")



all_corr          = {}
all_delta_summary = {}

for tagger_name, human_col, model_col in TAGGERS:
    # Пропустить pymorphy, если библиотека не установлена
    if tagger_name == "pymorphy" and not PYMO_AVAILABLE:
        print("[SKIP] pymorphy3 не установлен, пропускаем pymorphy tagger.")
        continue

    # Создаём копию human для этого tagger'а, чтобы не портить оригинал
    human_work = human_raw.copy()

    # Если нужная колонка отсутствует в human, пробуем вычислить
    if human_col not in human_work.columns:
        if tagger_name == "pymorphy" and "answer" in human_work.columns:
            print(f"  Вычисляем {human_col} для human с помощью pymorphy3 (оригинальные теги)...")
            human_work[human_col] = human_work["answer"].apply(get_pymorphy_tag)
        else:
            print(f"[SKIP] Колонка '{human_col}' не найдена в human и не может быть вычислена.")
            continue

    for model_name, model_df in get_all_models().items():
        model_work = model_df.copy()

        # Если нужная колонка отсутствует в model, пробуем вычислить
        if model_col not in model_work.columns:
            if tagger_name == "pymorphy" and "prediction_cleaned" in model_work.columns:
                print(f"  Вычисляем {model_col} для model '{model_name}' с помощью pymorphy3 (оригинальные теги)...")
                model_work[model_col] = model_work["prediction_cleaned"].apply(get_pymorphy_tag)
            else:
                print(f"[SKIP] Колонка '{model_col}' не найдена в {model_name} и не может быть вычислена.")
                continue

        model_slug = model_name.replace(" ", "_").replace("-", "_")
        out_dir = ROOT / f"{tagger_name}_{model_slug}"

        print(f"\n{'='*60}")
        print(f"  Tagger: {tagger_name}  |  Model: {model_name}")
        print(f"{'='*60}")

        corr_df, delta, mean_delta_ctx, overall_delta = run_corr(
            human_work, model_work, human_col, model_col, out_dir
        )

        label = f"{tagger_name} — {model_name}"
        all_corr[label]          = corr_df
        all_delta_summary[label] = overall_delta

ROOT.mkdir(parents=True, exist_ok=True)
if all_corr:
    plot_correlation_all(all_corr, ROOT / "fig_correlation_all.png")
if all_delta_summary:
    plot_delta_all(all_delta_summary, ROOT / "fig_delta_all.png")

print("\nDone.")
