# -*- coding: utf-8 -*-
"""analysis_pos_overlaap_with_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c53MqJU9tspYaefFtQKiKYl48p1mVOAy
"""

"""
analysis_pos_overlap.py

Algorithm 1: ranked POS intersection@k.

Runs for every model in get_all_models() and for both taggers:
  - stanza  (upos_answer / upos_word)
  - pymorphy (pymorphy_pos — computed on the fly if missing, original tags)

Outputs → output/pos_overlap/{tagger}_{model_slug}/
  human_pos_distribution.csv
  model_pos_distribution.csv
  per_context_results.csv
  summary.csv
  fig_intersection_k.png
"""
!pip install pymorphy3
import pathlib
import warnings

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from filter_data_llama_6 import get_all_models, load_human

import pymorphy3

MORPH = pymorphy3.MorphAnalyzer()



def get_pymorphy_tag(word: str) -> str:
    """Return original pymorphy3 POS tag (e.g., 'NOUN', 'ADJF', 'VERB', etc.)"""
    if not PYMO_AVAILABLE or not isinstance(word, str) or not word.strip():
        return None
    parsed = MORPH.parse(word)[0]
    return parsed.tag.POS  # ← исходный тег, без маппинга



K_VALUES = [1, 2, 3, 4, 5]
ROOT = pathlib.Path("output/pos_overlap")

# (tagger_name, human_col, model_col)
TAGGERS = [
    ("stanza", "upos_answer", "upos_word"),
    ("pymorphy", "pymorphy_pos", "pymorphy_pos"),
]


human_raw = load_human()

context_lookup = (
    human_raw.drop_duplicates("word.id")[["word.id", "Left context"]]
    .rename(columns={"word.id": "target_word", "Left context": "left_context"})
)


def ranked_pos(pos_df: pd.DataFrame) -> dict:
    out = {}
    for wid, grp in pos_df.groupby("word_id"):
        ordered = grp.sort_values("weight", ascending=False)["pos"].tolist()
        out[wid] = ordered
    return out


def run_overlap(human_df, model_df, human_pos_col, model_pos_col, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)

    #  human POS distribution
    human_dedup = (
        human_df.groupby(["word.id", "answer"], as_index=False)
        .first()[["word.id", "answer", human_pos_col, "probability_y"]]
    )
    human_pos = (
        human_dedup.groupby(["word.id", human_pos_col], as_index=False)["probability_y"]
        .sum()
        .rename(columns={"word.id": "word_id", human_pos_col: "pos", "probability_y": "weight"})
    )

    #model POS distribution 
    model_sorted = model_df.sort_values("probability_converted", ascending=False)
    model_dedup = model_sorted.drop_duplicates(
        subset=["target_word_id", "prediction_cleaned"], keep="first"
    )
    model_dedup = model_dedup[
        ["target_word_id", "prediction_cleaned", model_pos_col, "probability_converted"]
    ].dropna(subset=[model_pos_col])

    model_pos = (
        model_dedup.groupby(["target_word_id", model_pos_col], as_index=False)[
            "probability_converted"
        ]
        .sum()
        .rename(
            columns={
                "target_word_id": "word_id",
                model_pos_col: "pos",
                "probability_converted": "weight",
            }
        )
    )

  
    human_ranked = ranked_pos(human_pos)
    model_ranked = ranked_pos(model_pos)
    all_contexts = sorted(set(human_ranked) & set(model_ranked))
    print(f"  Shared contexts: {len(all_contexts)}")
    rows = []
    for ctx in all_contexts:
        h_rank = human_ranked[ctx]
        m_rank = model_ranked[ctx]
        row = {
            "word_id": ctx,
            "human_top_pos": h_rank[0] if h_rank else None,
            "model_top_pos": m_rank[0] if m_rank else None,
            "pos_match_at_1": int(bool(h_rank) and bool(m_rank) and h_rank[0] == m_rank[0]),
        }
        for k in K_VALUES:
            h_set = set(h_rank[:k])
            m_set = set(m_rank[:k])
            row[f"pos_intersection_at_{k}"] = len(h_set & m_set) / k
        rows.append(row)

    results = pd.DataFrame(rows)


    (
        human_pos.rename(columns={"word_id": "target_word", "pos": "upos", "weight": "probability"})
        .merge(context_lookup, on="target_word", how="left")[
            ["left_context", "target_word", "upos", "probability"]
        ]
        .to_csv(out_dir / "human_pos_distribution.csv", index=False)
    )
    (
        model_pos.rename(columns={"word_id": "target_word", "pos": "upos", "weight": "probability"})
        .merge(context_lookup, on="target_word", how="left")[
            ["left_context", "target_word", "upos", "probability"]
        ]
        .to_csv(out_dir / "model_pos_distribution.csv", index=False)
    )


    results_out = results.rename(columns={"word_id": "target_word"}).merge(
        context_lookup, on="target_word", how="left"
    )
    cols = ["left_context", "target_word"] + [
        c for c in results_out.columns if c not in ("left_context", "target_word")
    ]
    results_out[cols].to_csv(out_dir / "per_context_results.csv", index=False)

    summary_rows = []
    for k in K_VALUES:
        row = {
            "k": k,
            "mean_pos_match_at_1": results["pos_match_at_1"].mean() if k == 1 else None,
            "mean_pos_intersection_at_k": results[f"pos_intersection_at_{k}"].mean(),
        }
        summary_rows.append(row)
    pd.DataFrame(summary_rows).to_csv(out_dir / "summary.csv", index=False)

    print(f"  POS match@1: {results['pos_match_at_1'].mean():.4f}")
    for k in K_VALUES:
        print(f"  intersection@{k}: {results[f'pos_intersection_at_{k}'].mean():.4f}")

    return results


def plot_intersection_k(all_results: dict, out_path: pathlib.Path):
    fig, ax = plt.subplots(figsize=(8, 5))
    colors = ["#2166ac", "#d6604d", "#4dac26", "#8c510a", "#762a83", "#e08214"]
    markers = ["o", "s", "^", "D", "v", "P"]
    for (label, results), color, marker in zip(all_results.items(), colors, markers):
        vals = [results[f"pos_intersection_at_{k}"].mean() for k in K_VALUES]
        ax.plot(K_VALUES, vals, marker=marker, color=color, linewidth=2, markersize=7, label=label)
        for k, v in zip(K_VALUES, vals):
            ax.annotate(f"{v:.3f}", (k, v), textcoords="offset points", xytext=(5, 4), fontsize=7.5, color=color)
    ax.set_xlabel("k", fontsize=10)
    ax.set_ylabel("Mean POS intersection@k", fontsize=10)
    ax.set_title("POS intersection@k: stanza vs pymorphy3 (original tags)", fontsize=11)
    ax.set_xticks(K_VALUES)
    ax.legend(fontsize=8.5, framealpha=0.9)
    ax.grid(alpha=0.3)
    ax.set_ylim(0.2, 0.75)
    plt.tight_layout()
    plt.savefig(out_path, dpi=160, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {out_path}")


# ── main loop ─────────────────────────────────────────────────────────
all_results = {}

for tagger_name, human_col, model_col in TAGGERS:
    # Skip pymorphy if library not available
    if tagger_name == "pymorphy" and not PYMO_AVAILABLE:
        print("[SKIP] pymorphy3 not installed, skipping pymorphy tagger.")
        continue

    # Make a copy of human data for this tagger to avoid polluting original
    human_work = human_raw.copy()

    # Ensure human column exists (compute if missing)
    if human_col not in human_work.columns:
        if tagger_name == "pymorphy" and "answer" in human_work.columns:
            print(f"  Computing {human_col} for human data using pymorphy3 (original tags)...")
            human_work[human_col] = human_work["answer"].apply(get_pymorphy_tag)
        else:
            print(f"[SKIP] Column '{human_col}' not found in human data and cannot compute.")
            continue

    for model_name, model_df in get_all_models().items():
        # Work on a copy of model data as well
        model_work = model_df.copy()

        # Ensure model column exists (compute if missing)
        if model_col not in model_work.columns:
            if tagger_name == "pymorphy" and "prediction_cleaned" in model_work.columns:
                print(f"  Computing {model_col} for model '{model_name}' using pymorphy3 (original tags)...")
                model_work[model_col] = model_work["prediction_cleaned"].apply(get_pymorphy_tag)
            else:
                print(f"[SKIP] Column '{model_col}' not found in {model_name} data and cannot compute.")
                continue

        model_slug = model_name.replace(" ", "_").replace("-", "_")
        out_dir = ROOT / f"{tagger_name}_{model_slug}"

        print(f"\n{'='*60}")
        print(f"  Tagger: {tagger_name}  |  Model: {model_name}")
        print(f"{'='*60}")

        results = run_overlap(
            human_work,
            model_work,
            human_col,
            model_col,
            out_dir,
        )

        label = f"{tagger_name} — {model_name}"
        all_results[label] = results

# ── combined plot ──────────────────────────────────────────────────────
ROOT.mkdir(parents=True, exist_ok=True)
plot_intersection_k(all_results, ROOT / "fig_intersection_k_all.png")
print("\nDone.")
