# -*- coding: utf-8 -*-
"""analisys_entrophy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2GLWX7h5Pp33zxHgnfB7s98j1g_WTqd
"""

"""
analysis_entropy.py
-------------------
Энтропийный анализ контекстов и лемматический overlap.

Энтропия Шеннона вычисляется ТОЛЬКО по распределению ответов людей
и используется как характеристика контекста (степень его открытости),
а не как свойство модели.

Для каждого контекста вычисляется:
  - H_human            — энтропия Шеннона по распределению ответов людей
  - n_human_unique     — число уникальных ответов людей
  - overlap@k          — доля лемм человеческих ответов, найденных
                         в топ-k предсказаний модели (невзвешенная)
  - weighted_overlap@k — сумма вероятностей человеческих ответов,
                         леммы которых найдены в топ-k модели

Контексты разбиваются на квартили по H_human (Q1 = закрытые, Q4 = открытые).

Входные файлы задаются через get_all_models() и load_human().

Выходные файлы → output/entropy/
  per_context_entropy_human.csv   — H_human по контекстам
                                    (используется в analysis_semantic.py)
  per_context_entropy_<model>.csv — H_human + overlap для каждой модели
  quartile_summary_<model>.csv    — квартильная сводка overlap по H_human
"""

from pathlib import Path

import numpy as np
import pandas as pd

from filter_data_llama_6 import load_human, get_all_models

K_VALUES = [5, 10, 20, 50, 100]
OUT = Path("output/entropy")
OUT.mkdir(parents=True, exist_ok=True)


# ════════════════════════════════════════════════════════════════════
# ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ
# ════════════════════════════════════════════════════════════════════

def shannon_entropy(probs: pd.Series) -> float:
    """
    H = -sum(p_i * ln(p_i)) для p_i > 0.
    Вероятности нормализуются перед вычислением.
    """
    p = np.array(probs, dtype=float)
    p = p[p > 0]
    if p.sum() < 1e-9:
        return 0.0
    p = p / p.sum()
    return float(-np.sum(p * np.log(p)))


# ════════════════════════════════════════════════════════════════════
# ЗАГРУЗКА ДАННЫХ
# ════════════════════════════════════════════════════════════════════

people = load_human()

context_lookup = (
    people.drop_duplicates("word.id")[["word.id", "Left context"]]
    .rename(columns={"word.id": "target_word", "Left context": "left_context"})
)

# ── Human: дедупликация по поверхностной форме ───────────────────────
human_deduped = (
    people
    .assign(answer_stripped=people["answer"].str.strip())
    .drop_duplicates(subset=["word.id", "answer_stripped"])
)

# ── H_human — единственная энтропия в анализе ────────────────────────
H_human = (
    human_deduped
    .groupby("word.id")["probability_y"]
    .apply(shannon_entropy)
    .rename("H_human")
)

n_human_unique = (
    human_deduped.groupby("word.id")["answer_stripped"]
    .nunique()
    .rename("n_human_unique")
)

# ── Базовый датафрейм контекстов ─────────────────────────────────────
context_df = (
    pd.DataFrame({"H_human": H_human, "n_human_unique": n_human_unique})
    .reset_index()
    .rename(columns={"word.id": "word_id"})
)

# Квартили по H_human — общие для всех моделей
context_df["entropy_quartile"] = pd.qcut(
    context_df["H_human"], 4, labels=["Q1", "Q2", "Q3", "Q4"]
)

print(f"Контекстов: {len(context_df)}")
print(f"Mean H_human = {context_df['H_human'].mean():.4f}")

# ── Сохраняем H_human отдельно (нужен analysis_semantic.py) ──────────
h_human_export = (
    context_df[["word_id", "H_human"]]
    .rename(columns={"word_id": "target_word"})
)
h_human_export.to_csv(OUT / "per_context_entropy_human.csv", index=False)
print(f"Written {len(h_human_export)} rows → per_context_entropy_human.csv")


# ════════════════════════════════════════════════════════════════════
# ОСНОВНОЙ ЦИКЛ: по моделям
# ════════════════════════════════════════════════════════════════════

for model_name, model_df in get_all_models().items():
    print(f"\n{'=' * 55}")
    print(f"  Модель: {model_name}")
    print(f"{'=' * 55}")

    model_slug = model_name.replace(" ", "_").replace("-", "_")

    # дедупликация предсказаний по поверхностной форме
    model_sorted = model_df.sort_values("probability_converted", ascending=False)

    # ── Лемматический overlap@k ───────────────────────────────────────
    # дедупликация по лемме: берём предсказание с наивысшей вероятностью
    model_lemma_deduped = (
        model_sorted
        .drop_duplicates(subset=["target_word_id", "lemma_word"], keep="first")
        .groupby("target_word_id", sort=False)
        .apply(lambda df: df["lemma_word"].tolist(), include_groups=False)
        .rename("model_lemmas")
    )

    records = []
    for word_id, model_lemmas in model_lemma_deduped.items():
        ppl = people[people["word.id"] == word_id]
        if len(ppl) == 0:
            continue

        # Human: дедупликация поверхностных форм → группировка по лемме → сумма вероятностей
        answer_level = (
            ppl
            .assign(
                answer_stripped=ppl["answer"].str.strip(),
                lemma_stripped=ppl["lemma_answer"].astype(str).str.strip(),
            )
            .drop_duplicates(subset=["answer_stripped"])
            [["answer_stripped", "lemma_stripped", "probability_y"]]
        )
        lemma_prob = (
            answer_level
            .groupby("lemma_stripped")["probability_y"]
            .sum()
            .to_dict()
        )
        human_lemmas = set(lemma_prob.keys())

        row = {"word_id": word_id}
        for k in K_VALUES:
            top_k = set(model_lemmas[:k])
            found = human_lemmas & top_k
            row[f"overlap_at_{k}"] = (
                len(found) / len(human_lemmas) if human_lemmas else 0.0
            )
            row[f"weighted_overlap_at_{k}"] = sum(
                lemma_prob[lem] for lem in found
            )
        records.append(row)

    overlap_df = pd.DataFrame(records)

    # ── Финальный датафрейм ───────────────────────────────────────────
    result = context_df.merge(overlap_df, on="word_id")
    print(f"  Общих контекстов: {len(result)}")

    # ── Сохраняем per_context ─────────────────────────────────────────
    overlap_cols = (
        [f"overlap_at_{k}" for k in K_VALUES] +
        [f"weighted_overlap_at_{k}" for k in K_VALUES]
    )
    per_context = (
        result
        .rename(columns={"word_id": "target_word"})
        .merge(context_lookup, on="target_word")
        [["left_context", "target_word", "entropy_quartile",
          "H_human", "n_human_unique"] + overlap_cols]
    )
    fname = f"per_context_entropy_{model_slug}.csv"
    per_context.to_csv(OUT / fname, index=False)
    print(f"  Written {len(per_context)} rows → {fname}")

    # ── Квартильная сводка ────────────────────────────────────────────
    summary_cols = (
        ["H_human"] +
        [f"overlap_at_{k}" for k in K_VALUES] +
        [f"weighted_overlap_at_{k}" for k in K_VALUES]
    )
    summary = (
        result
        .groupby("entropy_quartile", observed=True)[summary_cols]
        .mean()
        .round(4)
        .reset_index()
        .rename(columns={
            "entropy_quartile": "quartile",
            "H_human": "mean_H_human",
        })
    )
    qname = f"quartile_summary_{model_slug}.csv"
    summary.to_csv(OUT / qname, index=False)
    print(f"  Written {len(summary)} rows → {qname}")

    # ── Печать сводки ─────────────────────────────────────────────────
    print(f"\n  Квартильная сводка [{model_name}]:")
    header = f"  {'Q':>4}  {'H_human':>8}"
    for k in K_VALUES:
        header += f"  {'ov@'+str(k):>8}"
    print(header)
    print("  " + "-" * (len(header) - 2))

    for _, row in summary.iterrows():
        line = f"  {row['quartile']:>4}  {row['mean_H_human']:>8.4f}"
        for k in K_VALUES:
            line += f"  {row[f'overlap_at_{k}']:>8.3f}"
        print(line)

print(f"\n✓ Готово. Файлы → {OUT}/")

"""
analysis_entropy_human.py
--------------------------
Анализ распределения энтропии человеческих ответов по контекстам.

Вычисляет:
  - дескриптивную статистику H_human
  - распределение по квартилям с примерами контекстов
  - гистограмму H_human
  - корреляцию H_human с числом уникальных ответов
  - примеры самых закрытых и самых открытых контекстов

Выходные файлы → output/entropy/
  entropy_human_stats.csv        — дескриптивная статистика
  entropy_human_quartiles.csv    — квартили с примерами контекстов
  fig_entropy_distribution.png   — гистограмма
  fig_entropy_vs_nunique.png     — scatter H_human vs n_unique
"""

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

from filter_data_llama_6 import load_human

OUT = Path("output/entropy")
OUT.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "font.family":       "DejaVu Sans",
    "font.size":         10,
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.alpha":        0.3,
    "grid.linestyle":    "--",
    "figure.dpi":        150,
})

BLUE = "#2B6CB0"
GRAY = "#718096"


# ════════════════════════════════════════════════════════════════════
# ЗАГРУЗКА
# ════════════════════════════════════════════════════════════════════

people = load_human()

context_lookup = (
    people.drop_duplicates("word.id")[["word.id", "Left context"]]
    .rename(columns={"word.id": "word_id", "Left context": "left_context"})
)

human_deduped = (
    people
    .assign(answer_stripped=people["answer"].str.strip())
    .drop_duplicates(subset=["word.id", "answer_stripped"])
)


def shannon_entropy(probs: pd.Series) -> float:
    p = np.array(probs, dtype=float)
    p = p[p > 0]
    if p.sum() < 1e-9:
        return 0.0
    p = p / p.sum()
    return float(-np.sum(p * np.log(p)))


H_human = (
    human_deduped
    .groupby("word.id")["probability_y"]
    .apply(shannon_entropy)
    .rename("H_human")
    .reset_index()
    .rename(columns={"word.id": "word_id"})
)

n_unique = (
    human_deduped.groupby("word.id")["answer_stripped"]
    .nunique()
    .rename("n_unique")
    .reset_index()
    .rename(columns={"word.id": "word_id"})
)

df = H_human.merge(n_unique, on="word_id").merge(context_lookup, on="word_id")
df["entropy_quartile"] = pd.qcut(
    df["H_human"], 4, labels=["Q1", "Q2", "Q3", "Q4"]
)


# ════════════════════════════════════════════════════════════════════
# 1. ДЕСКРИПТИВНАЯ СТАТИСТИКА
# ════════════════════════════════════════════════════════════════════

desc = df["H_human"].describe(percentiles=[0.25, 0.5, 0.75])
desc["skewness"] = df["H_human"].skew()
desc["kurtosis"] = df["H_human"].kurt()

stats_df = desc.rename("value").reset_index().rename(columns={"index": "stat"})
stats_df.to_csv(OUT / "entropy_human_stats.csv", index=False)

print("=== Дескриптивная статистика H_human ===")
print(stats_df.to_string(index=False))
print()


# ════════════════════════════════════════════════════════════════════
# 2. КВАРТИЛЬНАЯ ТАБЛИЦА С ПРИМЕРАМИ
# ════════════════════════════════════════════════════════════════════

quartile_stats = (
    df.groupby("entropy_quartile", observed=True)
    .agg(
        n_contexts=("word_id", "count"),
        H_min=("H_human", "min"),
        H_mean=("H_human", "mean"),
        H_max=("H_human", "max"),
        n_unique_mean=("n_unique", "mean"),
    )
    .round(4)
    .reset_index()
)

# Примеры: самый типичный контекст в каждом квартиле
# (контекст с H_human, ближайшей к среднему квартиля)
examples = []
for q in ["Q1", "Q2", "Q3", "Q4"]:
    sub = df[df["entropy_quartile"] == q].copy()
    mean_h = sub["H_human"].mean()
    closest = sub.iloc[(sub["H_human"] - mean_h).abs().argsort()[:1]]
    examples.append({
        "entropy_quartile": q,
        "example_context":  closest["left_context"].values[0],
        "example_H":        round(closest["H_human"].values[0], 4),
        "example_n_unique": int(closest["n_unique"].values[0]),
    })

examples_df = pd.DataFrame(examples)
quartile_full = quartile_stats.merge(examples_df, on="entropy_quartile")
quartile_full.to_csv(OUT / "entropy_human_quartiles.csv", index=False)

print("=== Квартили H_human ===")
print(quartile_full.to_string(index=False))
print()

# Экстремальные примеры
print("=== Самые закрытые контексты (H_human → 0) ===")
closed = df.nsmallest(5, "H_human")[["left_context", "H_human", "n_unique"]]
print(closed.to_string(index=False))
print()

print("=== Самые открытые контексты (H_human → max) ===")
opened = df.nlargest(5, "H_human")[["left_context", "H_human", "n_unique"]]
print(opened.to_string(index=False))
print()


# ════════════════════════════════════════════════════════════════════
# 3. ГИСТОГРАММА РАСПРЕДЕЛЕНИЯ H_human
# ════════════════════════════════════════════════════════════════════

fig, ax = plt.subplots(figsize=(8, 5))

ax.hist(df["H_human"], bins=20, color=BLUE, alpha=0.75, edgecolor="white")

# Вертикальные линии квартильных границ
q_bounds = df["H_human"].quantile([0.25, 0.5, 0.75])
for i, (q_val, label) in enumerate(
    zip(q_bounds, ["Q1/Q2", "Q2/Q3", "Q3/Q4"])
):
    ax.axvline(q_val, color=GRAY, linewidth=1.2, linestyle="--")
    ax.text(q_val + 0.03, ax.get_ylim()[1] * 0.85 - i * 3,
            label, color=GRAY, fontsize=9)

ax.axvline(df["H_human"].mean(), color=BLUE, linewidth=1.5, linestyle="-",
           label=f"Mean = {df['H_human'].mean():.2f}")

ax.set_xlabel("H_human (энтропия контекста)", fontsize=11)
ax.set_ylabel("Число контекстов", fontsize=11)
ax.set_title("Распределение энтропии человеческих ответов",
             fontsize=12, fontweight="bold")
ax.legend(fontsize=10)
plt.tight_layout()
plt.savefig(OUT / "fig_entropy_distribution.png", bbox_inches="tight")
plt.close()
print("Saved fig_entropy_distribution.png")


# ════════════════════════════════════════════════════════════════════
# 4. SCATTER: H_human vs n_unique
# ════════════════════════════════════════════════════════════════════

r, p = stats.pearsonr(df["H_human"], df["n_unique"])
r_s, p_s = stats.spearmanr(df["H_human"], df["n_unique"])

fig, ax = plt.subplots(figsize=(6, 5))
ax.scatter(df["n_unique"], df["H_human"],
           alpha=0.55, s=35, color=BLUE, zorder=3)

z = np.polyfit(df["n_unique"], df["H_human"], 1)
x_line = np.linspace(df["n_unique"].min(), df["n_unique"].max(), 100)
ax.plot(x_line, np.polyval(z, x_line),
        color="black", linewidth=1.5, linestyle="--")

ax.set_xlabel("Число уникальных ответов людей", fontsize=11)
ax.set_ylabel("H_human", fontsize=11)
ax.set_title(
    f"H_human vs число уникальных ответов\n"
    f"Pearson r = {r:.3f} (p = {p:.4f}), Spearman ρ = {r_s:.3f} (p = {p_s:.4f})",
    fontsize=10, fontweight="bold"
)
plt.tight_layout()
plt.savefig(OUT / "fig_entropy_vs_nunique.png", bbox_inches="tight")
plt.close()
print("Saved fig_entropy_vs_nunique.png")

print(f"\n✓ Готово. Файлы → {OUT}/")